/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UseCasesIndexRouteImport } from './routes/use-cases/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as UseCasesSlugRouteImport } from './routes/use-cases/$slug'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardNewRouteImport } from './routes/dashboard/new'
import { Route as DashboardMonitorsRouteImport } from './routes/dashboard/monitors'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as CompareVisualpingAlternativeRouteImport } from './routes/compare/visualping-alternative'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as DashboardMonitorIdIndexRouteImport } from './routes/dashboard/$monitorId/index'
import { Route as DashboardMonitorIdSettingsRouteImport } from './routes/dashboard/$monitorId/settings'
import { Route as AuthSignUpSplatRouteImport } from './routes/auth/sign-up.$'
import { Route as AuthSignInSplatRouteImport } from './routes/auth/sign-in.$'

const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesIndexRoute = UseCasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UseCasesRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const UseCasesSlugRoute = UseCasesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => UseCasesRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewRoute = DashboardNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonitorsRoute = DashboardMonitorsRouteImport.update({
  id: '/monitors',
  path: '/monitors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const CompareVisualpingAlternativeRoute =
  CompareVisualpingAlternativeRouteImport.update({
    id: '/compare/visualping-alternative',
    path: '/compare/visualping-alternative',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMonitorIdIndexRoute = DashboardMonitorIdIndexRouteImport.update({
  id: '/$monitorId/',
  path: '/$monitorId/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonitorIdSettingsRoute =
  DashboardMonitorIdSettingsRouteImport.update({
    id: '/$monitorId/settings',
    path: '/$monitorId/settings',
    getParentRoute: () => DashboardRoute,
  } as any)
const AuthSignUpSplatRoute = AuthSignUpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthSignUpRoute,
} as any)
const AuthSignInSplatRoute = AuthSignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthSignInRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/use-cases': typeof UseCasesRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/visualping-alternative': typeof CompareVisualpingAlternativeRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/monitors': typeof DashboardMonitorsRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/use-cases/': typeof UseCasesIndexRoute
  '/auth/sign-in/$': typeof AuthSignInSplatRoute
  '/auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/dashboard/$monitorId/settings': typeof DashboardMonitorIdSettingsRoute
  '/dashboard/$monitorId/': typeof DashboardMonitorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/auth/sign-in': typeof AuthSignInRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/visualping-alternative': typeof CompareVisualpingAlternativeRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/monitors': typeof DashboardMonitorsRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/use-cases': typeof UseCasesIndexRoute
  '/auth/sign-in/$': typeof AuthSignInSplatRoute
  '/auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/dashboard/$monitorId/settings': typeof DashboardMonitorIdSettingsRoute
  '/dashboard/$monitorId': typeof DashboardMonitorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/use-cases': typeof UseCasesRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/visualping-alternative': typeof CompareVisualpingAlternativeRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/monitors': typeof DashboardMonitorsRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/use-cases/': typeof UseCasesIndexRoute
  '/auth/sign-in/$': typeof AuthSignInSplatRoute
  '/auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/dashboard/$monitorId/settings': typeof DashboardMonitorIdSettingsRoute
  '/dashboard/$monitorId/': typeof DashboardMonitorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/dashboard'
    | '/features'
    | '/pricing'
    | '/use-cases'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/blog/$slug'
    | '/compare/visualping-alternative'
    | '/dashboard/admin'
    | '/dashboard/monitors'
    | '/dashboard/new'
    | '/dashboard/settings'
    | '/use-cases/$slug'
    | '/blog/'
    | '/dashboard/'
    | '/use-cases/'
    | '/auth/sign-in/$'
    | '/auth/sign-up/$'
    | '/dashboard/$monitorId/settings'
    | '/dashboard/$monitorId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features'
    | '/pricing'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/blog/$slug'
    | '/compare/visualping-alternative'
    | '/dashboard/admin'
    | '/dashboard/monitors'
    | '/dashboard/new'
    | '/dashboard/settings'
    | '/use-cases/$slug'
    | '/blog'
    | '/dashboard'
    | '/use-cases'
    | '/auth/sign-in/$'
    | '/auth/sign-up/$'
    | '/dashboard/$monitorId/settings'
    | '/dashboard/$monitorId'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/dashboard'
    | '/features'
    | '/pricing'
    | '/use-cases'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/blog/$slug'
    | '/compare/visualping-alternative'
    | '/dashboard/admin'
    | '/dashboard/monitors'
    | '/dashboard/new'
    | '/dashboard/settings'
    | '/use-cases/$slug'
    | '/blog/'
    | '/dashboard/'
    | '/use-cases/'
    | '/auth/sign-in/$'
    | '/auth/sign-up/$'
    | '/dashboard/$monitorId/settings'
    | '/dashboard/$monitorId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  UseCasesRoute: typeof UseCasesRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRouteWithChildren
  AuthSignUpRoute: typeof AuthSignUpRouteWithChildren
  CompareVisualpingAlternativeRoute: typeof CompareVisualpingAlternativeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/': {
      id: '/use-cases/'
      path: '/'
      fullPath: '/use-cases/'
      preLoaderRoute: typeof UseCasesIndexRouteImport
      parentRoute: typeof UseCasesRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/use-cases/$slug': {
      id: '/use-cases/$slug'
      path: '/$slug'
      fullPath: '/use-cases/$slug'
      preLoaderRoute: typeof UseCasesSlugRouteImport
      parentRoute: typeof UseCasesRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/new': {
      id: '/dashboard/new'
      path: '/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof DashboardNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/monitors': {
      id: '/dashboard/monitors'
      path: '/monitors'
      fullPath: '/dashboard/monitors'
      preLoaderRoute: typeof DashboardMonitorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/compare/visualping-alternative': {
      id: '/compare/visualping-alternative'
      path: '/compare/visualping-alternative'
      fullPath: '/compare/visualping-alternative'
      preLoaderRoute: typeof CompareVisualpingAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$monitorId/': {
      id: '/dashboard/$monitorId/'
      path: '/$monitorId'
      fullPath: '/dashboard/$monitorId/'
      preLoaderRoute: typeof DashboardMonitorIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$monitorId/settings': {
      id: '/dashboard/$monitorId/settings'
      path: '/$monitorId/settings'
      fullPath: '/dashboard/$monitorId/settings'
      preLoaderRoute: typeof DashboardMonitorIdSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/sign-up/$': {
      id: '/auth/sign-up/$'
      path: '/$'
      fullPath: '/auth/sign-up/$'
      preLoaderRoute: typeof AuthSignUpSplatRouteImport
      parentRoute: typeof AuthSignUpRoute
    }
    '/auth/sign-in/$': {
      id: '/auth/sign-in/$'
      path: '/$'
      fullPath: '/auth/sign-in/$'
      preLoaderRoute: typeof AuthSignInSplatRouteImport
      parentRoute: typeof AuthSignInRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardMonitorsRoute: typeof DashboardMonitorsRoute
  DashboardNewRoute: typeof DashboardNewRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardMonitorIdSettingsRoute: typeof DashboardMonitorIdSettingsRoute
  DashboardMonitorIdIndexRoute: typeof DashboardMonitorIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardMonitorsRoute: DashboardMonitorsRoute,
  DashboardNewRoute: DashboardNewRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardMonitorIdSettingsRoute: DashboardMonitorIdSettingsRoute,
  DashboardMonitorIdIndexRoute: DashboardMonitorIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface UseCasesRouteChildren {
  UseCasesSlugRoute: typeof UseCasesSlugRoute
  UseCasesIndexRoute: typeof UseCasesIndexRoute
}

const UseCasesRouteChildren: UseCasesRouteChildren = {
  UseCasesSlugRoute: UseCasesSlugRoute,
  UseCasesIndexRoute: UseCasesIndexRoute,
}

const UseCasesRouteWithChildren = UseCasesRoute._addFileChildren(
  UseCasesRouteChildren,
)

interface AuthSignInRouteChildren {
  AuthSignInSplatRoute: typeof AuthSignInSplatRoute
}

const AuthSignInRouteChildren: AuthSignInRouteChildren = {
  AuthSignInSplatRoute: AuthSignInSplatRoute,
}

const AuthSignInRouteWithChildren = AuthSignInRoute._addFileChildren(
  AuthSignInRouteChildren,
)

interface AuthSignUpRouteChildren {
  AuthSignUpSplatRoute: typeof AuthSignUpSplatRoute
}

const AuthSignUpRouteChildren: AuthSignUpRouteChildren = {
  AuthSignUpSplatRoute: AuthSignUpSplatRoute,
}

const AuthSignUpRouteWithChildren = AuthSignUpRoute._addFileChildren(
  AuthSignUpRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  UseCasesRoute: UseCasesRouteWithChildren,
  AuthSignInRoute: AuthSignInRouteWithChildren,
  AuthSignUpRoute: AuthSignUpRouteWithChildren,
  CompareVisualpingAlternativeRoute: CompareVisualpingAlternativeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
