/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardNewRouteImport } from './routes/dashboard/new'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as DashboardMonitorIdIndexRouteImport } from './routes/dashboard/$monitorId/index'
import { Route as DashboardMonitorIdSettingsRouteImport } from './routes/dashboard/$monitorId/settings'
import { Route as AuthSignUpSplatRouteImport } from './routes/auth/sign-up.$'
import { Route as AuthSignInSplatRouteImport } from './routes/auth/sign-in.$'

const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNewRoute = DashboardNewRouteImport.update({
  id: '/dashboard/new',
  path: '/dashboard/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMonitorIdIndexRoute = DashboardMonitorIdIndexRouteImport.update({
  id: '/dashboard/$monitorId/',
  path: '/dashboard/$monitorId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMonitorIdSettingsRoute =
  DashboardMonitorIdSettingsRouteImport.update({
    id: '/dashboard/$monitorId/settings',
    path: '/dashboard/$monitorId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSignUpSplatRoute = AuthSignUpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthSignUpRoute,
} as any)
const AuthSignInSplatRoute = AuthSignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthSignInRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/auth/sign-in': typeof AuthSignInRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRouteWithChildren
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/sign-in/$': typeof AuthSignInSplatRoute
  '/auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/dashboard/$monitorId/settings': typeof DashboardMonitorIdSettingsRoute
  '/dashboard/$monitorId/': typeof DashboardMonitorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/auth/sign-in': typeof AuthSignInRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRouteWithChildren
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/sign-in/$': typeof AuthSignInSplatRoute
  '/auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/dashboard/$monitorId/settings': typeof DashboardMonitorIdSettingsRoute
  '/dashboard/$monitorId': typeof DashboardMonitorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/auth/sign-in': typeof AuthSignInRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRouteWithChildren
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/sign-in/$': typeof AuthSignInSplatRoute
  '/auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/dashboard/$monitorId/settings': typeof DashboardMonitorIdSettingsRoute
  '/dashboard/$monitorId/': typeof DashboardMonitorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/features'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/new'
    | '/dashboard/'
    | '/auth/sign-in/$'
    | '/auth/sign-up/$'
    | '/dashboard/$monitorId/settings'
    | '/dashboard/$monitorId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/new'
    | '/dashboard'
    | '/auth/sign-in/$'
    | '/auth/sign-up/$'
    | '/dashboard/$monitorId/settings'
    | '/dashboard/$monitorId'
  id:
    | '__root__'
    | '/'
    | '/features'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/new'
    | '/dashboard/'
    | '/auth/sign-in/$'
    | '/auth/sign-up/$'
    | '/dashboard/$monitorId/settings'
    | '/dashboard/$monitorId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeaturesRoute: typeof FeaturesRoute
  AuthSignInRoute: typeof AuthSignInRouteWithChildren
  AuthSignUpRoute: typeof AuthSignUpRouteWithChildren
  DashboardNewRoute: typeof DashboardNewRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardMonitorIdSettingsRoute: typeof DashboardMonitorIdSettingsRoute
  DashboardMonitorIdIndexRoute: typeof DashboardMonitorIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/new': {
      id: '/dashboard/new'
      path: '/dashboard/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof DashboardNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$monitorId/': {
      id: '/dashboard/$monitorId/'
      path: '/dashboard/$monitorId'
      fullPath: '/dashboard/$monitorId/'
      preLoaderRoute: typeof DashboardMonitorIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$monitorId/settings': {
      id: '/dashboard/$monitorId/settings'
      path: '/dashboard/$monitorId/settings'
      fullPath: '/dashboard/$monitorId/settings'
      preLoaderRoute: typeof DashboardMonitorIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up/$': {
      id: '/auth/sign-up/$'
      path: '/$'
      fullPath: '/auth/sign-up/$'
      preLoaderRoute: typeof AuthSignUpSplatRouteImport
      parentRoute: typeof AuthSignUpRoute
    }
    '/auth/sign-in/$': {
      id: '/auth/sign-in/$'
      path: '/$'
      fullPath: '/auth/sign-in/$'
      preLoaderRoute: typeof AuthSignInSplatRouteImport
      parentRoute: typeof AuthSignInRoute
    }
  }
}

interface AuthSignInRouteChildren {
  AuthSignInSplatRoute: typeof AuthSignInSplatRoute
}

const AuthSignInRouteChildren: AuthSignInRouteChildren = {
  AuthSignInSplatRoute: AuthSignInSplatRoute,
}

const AuthSignInRouteWithChildren = AuthSignInRoute._addFileChildren(
  AuthSignInRouteChildren,
)

interface AuthSignUpRouteChildren {
  AuthSignUpSplatRoute: typeof AuthSignUpSplatRoute
}

const AuthSignUpRouteChildren: AuthSignUpRouteChildren = {
  AuthSignUpSplatRoute: AuthSignUpSplatRoute,
}

const AuthSignUpRouteWithChildren = AuthSignUpRoute._addFileChildren(
  AuthSignUpRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeaturesRoute: FeaturesRoute,
  AuthSignInRoute: AuthSignInRouteWithChildren,
  AuthSignUpRoute: AuthSignUpRouteWithChildren,
  DashboardNewRoute: DashboardNewRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardMonitorIdSettingsRoute: DashboardMonitorIdSettingsRoute,
  DashboardMonitorIdIndexRoute: DashboardMonitorIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
